### ISSUE TITLE
Waiting for the detection KD code!

### ISSUE THREAD

**Issue by tjdhg456** [LiuDongyang6/FCFD#1]
Hi, thank you for your great work.

I'm waiting for your code about KD in object detection task.

Thank you !!

**Comment by LiuDongyang6** [comment]
Hi! Thank you for your interest in our work!

**Comment by LiuDongyang6** [comment]
Hi! Thank you for your interest in our work and your reminder!

The codes will be released very soon (in one day or two). We will inform you when it is done.

**Comment by tjdhg456** [comment]
Thank you for your kind remarks!!

**Comment by LiuDongyang6** [comment]
Hi! Detection codes have been released.

**Comment by tjdhg456** [comment]
Thank you very much!
